version: '3.8'

services:
  flutter_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: flutter-dev-image
    container_name: flutter-dev-container-try2
    restart: unless-stopped

    # DİKKAT: Bu ayar container'a ana makine üzerinde neredeyse tam yetki verir ve güvenlik riski taşır.
    privileged: true

    volumes:
      # Proje dizinini container içindeki /app'e bağla
      - .:/app
      # X11 soketini bağla (GUI çıktısı için - Temel X11)
      - /tmp/.X11-unix:/tmp/.X11-unix
      # XDG_RUNTIME_DIR kaldırıldı
      # - /run/user/${USER_UID}:/run/user/${USER_UID}
      # Cache Volume Önerileri (İsteğe Bağlı) - Yollar Root'a ayarlı
      - flutter-sdk-cache:/root/.config/flutter
      - android-sdk-cache:/root/.android
      - gradle-cache:/root/.gradle
      - pub-cache:/root/.pub-cache

    environment:
      - DISPLAY=${DISPLAY}
      # XDG_RUNTIME_DIR kaldırıldı
      # - XDG_RUNTIME_DIR=/run/user/${USER_UID}
      - ANDROID_SDK_ROOT=/root/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

    # Privileged modda cihaz bağlamasına gerek kalmadı
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb
    #   - /dev/dri:/dev/dri # Eğer grafik donanımı erişimi gerekirse eklenebilir

    # Port eşlemeleri (isteğe bağlı)
    # - "8080:8080"

# Cache Volume Tanımları (İsteğe Bağlı)
volumes:
  flutter-sdk-cache:
  android-sdk-cache:
  gradle-cache:
  pub-cache:
