version: '3.8'

services:
  flutter_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: flutter-dev-image
    container_name: flutter-dev-container-try2
    restart: unless-stopped

    # WARNING: This setting gives the container almost full authority on the host machine and carries a security risk.
    privileged: true

    volumes:
      # Mount the project directory to /app inside the container
      - .:/app
      # Mount the X11 socket (for GUI output - Basic X11)
      - /tmp/.X11-unix:/tmp/.X11-unix
      # XDG_RUNTIME_DIR removed
      # - /run/user/${USER_UID}:/run/user/${USER_UID}
      # Cache Volume Suggestions (Optional) - Paths set to Root
      - flutter-sdk-cache:/root/.config/flutter
      - android-sdk-cache:/root/.android
      - gradle-cache:/root/.gradle
      - pub-cache:/root/.pub-cache

    environment:
      - DISPLAY=${DISPLAY}
      # XDG_RUNTIME_DIR removed
      # - XDG_RUNTIME_DIR=/run/user/${USER_UID}
      - ANDROID_SDK_ROOT=/root/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

    # Device mapping is not needed in privileged mode
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb
    #   - /dev/dri:/dev/dri # Can be added if graphics hardware access is needed

    # Port mappings (optional)
    # - "8080:8080"

# Cache Volume Definitions (Optional)
volumes:
  flutter-sdk-cache:
  android-sdk-cache:
  gradle-cache:
  pub-cache: