version: '3.8'

services:
  flutter_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: flutter-dev-image
    container_name: flutter-dev-container_try
    restart: unless-stopped

    # === PRIVILEGED MODE ===
    # WARNING: CARRIES HIGH SECURITY RISK.
    # privileged: true # Commented out by default for security
    # =======================

    # === GPU Resources (Requires Nvidia Container Toolkit for Nvidia GPUs) ===
    # This section allows the container to access GPUs for hardware acceleration.
    # Uncomment this section ONLY if you have an Nvidia GPU AND the Nvidia Container Toolkit installed.
    # For AMD/Intel GPUs, different configurations might be needed (e.g., via device mapping if supported).
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all # Use all available GPUs
    #           capabilities: [gpu] # Request GPU capability
    # ==========================================================

    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - flutter-sdk-cache:/root/.config/flutter
      - android-sdk-cache:/root/.android
      - gradle-cache:/root/.gradle
      - pub-cache:/root/.pub-cache

      # KVM device is mapped (can be explicitly specified even if privileged mode guarantees it)
      - /dev/kvm:/dev/kvm

      # Graphics device is mapped (can be explicitly specified even if privileged mode guarantees it)
      # Generally not needed here if using deploy resources or privileged mode.
      # Might be needed for non-Nvidia GPUs if deploy resources doesn't work.
      # - /dev/dri:/dev/dri


    environment:
      - DISPLAY=${DISPLAY}
      - ANDROID_SDK_ROOT=/root/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      # Some display settings might be useful for the emulator (optional)
      # - QT_X11_NO_MITSHM=1
      # - _JAVA_AWT_WM_NONREPARENTING=1


    # Explicit device mappings (e.g., for USB devices or graphics if deploy/privileged is not used)
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb
    #   - /dev/dri:/dev/dri # Redundant if deploy resources or privileged is used


    # Port mappings (optional)
    # - "8080:8080"

volumes:
  flutter-sdk-cache:
  android-sdk-cache:
  gradle-cache:
  pub-cache: